### ISSUE TITLE
xCode 13, ios 15 - CBService error

### ISSUE THREAD

**Issue by mtoninelli** [franroberti95/react-native-aws-freertos#12]
After updating xCode to v13 for building ios 15 there is this issue:

```
(self.devices[peripheral.identifier]?.rxLotDataQueues[characteristic.service.uuid.uuidString]?.count ?? 0) in queue")
/Users/m/Library/Developer/Xcode/DerivedData/eehe-gjrdsvtxbhmdczgytlhaweozzgss/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AmazonFreeRTOS.build/Objects-normal/x86_64/AmazonFreeRTOSConstants.dia:1:1: warning: Could not read serialized diagnostics file: error("Invalid diagnostics signature") (in target 'AmazonFreeRTOS' from project 'Pods')
Command CompileSwift failed with a nonzero exit code
```

and 

```
AmazonFreeRTOS/AmazonFreeRTOS/AmazonFreeRTOSManager.swift:637:161: error: value of optional type 'CBService?' must be unwrapped to refer to member 'characteristicOf' of wrapped base type 'CBService'
                guard let characteristic = characteristic.service.characteristicOf(uuid: AmazonFreeRTOSGattCharacteristic.RXLargeMqttMessage) ?? characteristic.service.characteristicOf(uuid: AmazonFreeRTOSGattCharacteristic.RXLargeNetworkMessage) else {
```

any idea why is this happening?

**Comment by mtoninelli** [comment]
And this:
```
The following build commands failed:
        CompileSwift normal x86_64 /Users/m/Documents/Evergreen/APPS/EEHE/node_modules/react-native-aws-freertos/ios/AwsFreertos.swift (in target 'react-native-aws-freertos' from project 'Pods')
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'react-native-aws-freertos' from project 'Pods')
(2 failures)
```

**Comment by franroberti95** [comment]
You downloaded the latest version right ? I did a fix for that a month ago

**Comment by mtoninelli** [comment]
Thanks as usual for your quick reply! 
yes, I'm using v0.1.23.
I've just found a solution that fixed for me.
That https://github.com/react-native-community/upgrade-support/issues/62#issuecomment-622985723
